apiVersion: batch/v1
kind: Job
metadata:
  name: "dkube-upgrade-hook"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dkube-deployer.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "dkube-upgrade-hook"
      labels:
        {{- include "dkube-deployer.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: dkube-dockerhub-secret
      containers:
      - name: dkube-upgrade-hook
        image: {{ .Values.dkube.optional.dkubeRegistry }}/dkubeadm:{{ .Values.dkube.optional.dkubeVersion }}-helm
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command: ["/opt/dkubeadm/dkubeadm.sh", "dkube", "upgrade", {{ .Values.dkube.optional.dkubeVersion | quote}}]
      serviceAccountName: dkube-deployer-sa